### ISSUE TITLE
Errors while building after update to 7.0.4

### ISSUE THREAD

**Issue by john-hi** [web-dave/ngx-img-cropper#72]
ERROR in node_modules/ngx-img-cropper/lib/image-cropper/image-cropper.component.d.ts(4,30): error TS2307: Cannot find module './model/cropPosition'.
node_modules/ngx-img-cropper/lib/image-cropper/imageCropper.d.ts(1,24): error TS2307: Cannot find module './model/bounds'.node_modules/ngx-img-cropper/lib/image-cropper/imageCropper.d.ts(2,30): error TS2307: Cannot find module './model/cornerMarker'.
node_modules/ngx-img-cropper/lib/image-cropper/imageCropper.d.ts(3,27): error TS2307: Cannot find module './model/cropTouch'.
node_modules/ngx-img-cropper/lib/image-cropper/imageCropper.d.ts(5,28): error TS2307: Cannot find module './model/dragMarker'.
node_modules/ngx-img-cropper/lib/image-cropper/imageCropper.d.ts(6,35): error TS2307: Cannot find module './model/imageCropperModel'.
node_modules/ngx-img-cropper/lib/image-cropper/imageCropper.d.ts(7,23): error TS2307: Cannot find module './model/point'.
node_modules/ngx-img-cropper/public_api.d.ts(5,15): error TS2307: Cannot find module './lib/image-cropper/model/cropPosition'.

**Comment by web-dave** [comment]
Please post your package.json
It works with v7.x properly.
My showcase works fine with it
https://webdave.de/ngx-img-cropper
Try to reinstall your node_modukes.
Wich version was installed?
Does it work with `ng serve`?

**Comment by erizoy** [comment]
I have same problem with 7.0.4
Downgrade to 7.0.3 and build/serve works well.

**Comment by Pikadili83** [comment]
The same problem here after upgrading to 7.0.4.

ERROR in Couldn't resolve original symbol for ./lib/image-cropper/model/cropPosition from ../node_modules/ngx-img-cropper/ngx-img-cropper.d.ts

**Comment by Ryssa** [comment]
> Try to reinstall your node_modules

Already tried, it didn't work.

> Does it work with `ng serve`?

Nop.

> Which version was installed?

7.0.4. Downgrading to `7.0.3` works fine. 

package.json:

```
"dependencies": {
    "@angular-builders/custom-webpack": "^7.4.3",
    "@angular/animations": "^7.2.14",
    "@angular/common": "^7.2.14",
    "@angular/compiler": "^7.2.14",
    "@angular/core": "^7.2.14",
    "@angular/forms": "^7.2.14",
    "@angular/http": "^7.2.14",
    "@angular/platform-browser": "^7.2.14",
    "@angular/platform-browser-dynamic": "^7.2.14",
    "@angular/platform-server": "^7.2.14",
    "@angular/router": "^7.2.14",
    "@ng-select/ng-select": "^2.18.0",
    "@ngx-translate/core": "^11.0.1",
    "@types/file-saver": "^2.0.0",
    "angular-rollbar": "^0.1.3",
    "angular-sortablejs": "^2.7.0",
    "core-js": "2.6.5",
    "file-saver": "^2.0.1",
    "moment": "^2.24.0",
    "ng2-smooth-scroll": "^1.0.1",
    "ng5-slider": "^1.1.14",
    "ngx-img-cropper": "^7.0.3",
    "rxjs": "^6.5.1",
    "sortablejs": "^1.9.0",
    "tslib": "^1.9.3",
    "zone.js": "0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.8",
    "@angular/cli": "^7.3.8",
    "@angular/compiler-cli": "^7.2.14",
    "@angular/language-service": "^7.2.14",
    "@types/jasmine": "^3.3.12",
    "@types/jasminewd2": "^2.0.6",
    "@types/node": "^11.13.8",
    "codelyzer": "^5.0.1",
    "dotenv": "^7.0.0",
    "husky": "^2.1.0",
    "jasmine-core": "^3.4.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "^2.0.5",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "node-sass": "^4.12.0",
    "npm-run-all": "^4.1.5",
    "prettier": "^1.17.0",
    "pretty-quick": "^1.10.0",
    "protractor": "^5.4.2",
    "rxjs-tslint": "^0.1.7",
    "ts-node": "^8.1.0",
    "tslint": "^5.16.0",
    "tslint-config-airbnb": "^5.11.1",
    "tslint-config-prettier": "^1.18.0",
    "typescript": "3.1.1",
    "webpack-bundle-analyzer": "^3.3.2"
  }
```

**Comment by web-dave** [comment]
I'll check it. Sorry for this bug.

**Comment by web-dave** [comment]
Oh, there was a issue with my last build. I did it in the train, (german train have weak wifi) and there was a publish error. Published it again (same code but new version (7.0.5) it works with my webite (http://webdave.de/ngx-img-cropper) 
I was too optimistic about the wifi in the train.
Please test it and report the result here, so i can close it afterward.

**Comment by hugoj-goncalves** [comment]
same issue here with 7.0.4 and 7.0.5

**Comment by web-dave** [comment]
Can you reproduce it in a Stackblitz? I can't reproduce it here.

**Comment by hugoj-goncalves** [comment]
maybe I ran into some cache issues Idk, can't reproduce the error anymore.
everything is working fine again after 7.0.5
my bad.
