### ISSUE TITLE
Support Angular 7

### ISSUE THREAD

**Issue by Pikadili83** [web-dave/ngx-img-cropper#60]
Is there a plan to support Angular 7?

**Comment by web-dave** [comment]
Hi, I just merged the price.
Sorry for the delay. Unfortunately the company which published it to npm fired me and I have no access to the npm account. Is there a possibility to move a project from a company scope to a open scope?.

**Comment by Pikadili83** [comment]
Hi, thanks...
More details here [Transferring a repository](https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/)

**Comment by santiagoalmeidabolannos** [comment]
i am updating my angular 6 project to angular 7 and i get an error like this

`Package "ngx-img-cropper" has an incompatible peer dependency to "@angular/common" (requires ">=6.0.0-rc.0 <7.0.0||>=5.0.0 <6.0.0", would install "7.0.1").
Incompatible peer dependencies found. See above.`

**Comment by guillaume-ro-fr** [comment]
@santiagoalmeidabolannos : The package is not yet released, the old sources are still on npm registry.

**Comment by robert-king** [comment]
How do we install from git?

I tried:

`npm install https://github.com/web-dave/ngx-img-cropper/tarball/master --save`

but got:

```
ERROR in ./node_modules/ngx-img-cropper/index.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /Users/robertking/go/src/github.com/robert-king/intempo/node_modules/ngx-img-cropper/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/robertking/go/src/github.com/robert-king/intempo/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:753:23)
    at plugin.done.then (/Users/robertking/go/src/github.com/robert-king/intempo/node_modules/@ngtools/webpack/src/loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by web-dave** [comment]
Hi,
No answer from my ex employeer.
I need their support to switch this lip to out of their comany or set me as the owner.
I'm frustraited. feels like fighting against windmills.
What do you think about move it to a new npm project (git stays the same and im able to maintain)

**Comment by robert-king** [comment]
@web-dave  sorry to hear about your situation!  thanks for a great library.

**Comment by web-dave** [comment]
Hi. I'm the maintainer again. So I'll publish the latest version to npm today.

**Comment by robert-king** [comment]
Thanks a lot!

**Comment by web-dave** [comment]
Done. please checkout. and in any kind of issue, .... you know how to deal with it.
THX for your patience

**Comment by notarnet** [comment]
After the upgrade to 0.11.0 version I have the following bulding errors:
```
ERROR in node_modules/ngx-img-cropper/index.d.ts(6,24): error TS2307: Cannot find module './src/model/bounds'.
node_modules/ngx-img-cropper/index.d.ts(7,30): error TS2307: Cannot find module './src/model/cropPosition'.
node_modules/ngx-img-cropper/src/imageCropper.d.ts(1,24): error TS2307: Cannot find module './model/bounds'.
node_modules/ngx-img-cropper/src/imageCropper.d.ts(2,30): error TS2307: Cannot find module './model/cornerMarker'.
node_modules/ngx-img-cropper/src/imageCropper.d.ts(3,27): error TS2307: Cannot find module './model/cropTouch'.
node_modules/ngx-img-cropper/src/imageCropper.d.ts(5,28): error TS2307: Cannot find module './model/dragMarker'.
node_modules/ngx-img-cropper/src/imageCropper.d.ts(6,35): error TS2307: Cannot find module './model/imageCropperModel'.
node_modules/ngx-img-cropper/src/imageCropper.d.ts(7,23): error TS2307: Cannot find module './model/point'.
node_modules/ngx-img-cropper/src/imageCropperComponent.d.ts(4,30): error TS2307: Cannot find module './model/cropPosition'.
```
Someone else?

**Comment by web-dave** [comment]
Hi friends. Thx for your patien.
I just published the latest version. now this lib is build with @angular/cli and@angular ^7.2.0
